let ENV: any = process.env;
export const Args = {
  publicKey: ENV.PUBLIC_KEY || "",
  privateKey: ENV.PRIVATE_KEY || "",
  mode: ENV.MODE || "MANUAL",
  chatId: ENV.CHAT_ID || "",
  chartInterval: ENV.CHART_INTERVAL || "1h",
  stableToken: ENV.STABLE_TOKEN || "USDC",
  targetToken: ENV.TARGET_TOKEN || "WMATIC",
  stableTokenTickerKraken: ENV.STABLE_TOKEN_TICKER_KRAKEN || "USDCUSD",
  targetTokenTickerKraken: ENV.TARGET_TOKEN_TICKER_KRAKEN || "MATICUSD",
  botToken: ENV.BOT_TOKEN || "",
  password: ENV.PASSWORD || "kryptonite",
  redisAddress: ENV.REDIS_ADDRESS || "",
  chainId: Number(ENV.CHAIN_ID || 137),
  preAuth: Boolean(ENV.PRE_AUTH || false),
  stopLimitPercent: Math.abs(Number(ENV.STOP_LIMIT_PERCENT || 1)),
  buyBackLimitPercent: Math.abs(Number(ENV.BUY_BACK_LIMIT_PERCENT || 1)),
  maxStopLimitTriggers: Math.abs(Number(ENV.MAX_STOP_LOSS_TRIGGERS || 5)),
  slippagePercent: Number(ENV.SLIPPAGE_PERCENT || 1),
  port: Number(ENV.PORT || 8080),
};
